# Use the Alpine Linux base image
FROM alpine:latest

# Specify a volume at /data
VOLUME /data

# Default command to keep the container running and interactable
CMD ["sh", "-c", "while true; do sleep 1000; done"]
